version: '3.8'
services:
  keycloak:
    container_name: keycloak
    image: "quay.io/keycloak/keycloak:22.0.4"
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    command: ['start-dev','--import-realm']
    environment:
      JAVA_OPTS: "-Dkeycloak.profile=preview"
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME_URL: http://127.0.0.1:8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8080:8080"
      - "8787:8787" # debug port
    networks:
      - local-keycloak
  redis-cache:
    container_name: rediscache
    image: redis:6.2.7
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - local-keycloak
  word-finder-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - local-keycloak
    depends_on:
      - redis-cache
      - keycloak

networks:
  local-keycloak: {}
volumes:
  postgres_data: {}
